# Generated by Atsushi w/ Django 1.11 on 2018-03-19 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0007_preview_id_remove_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preview_id',
            field=models.UUIDField(default=uuid.uuid4, unique=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='preview_id',
            field=models.UUIDField(default=uuid.uuid4, unique=False),
        ),
    ]
