# Generated by Django 2.0.5 on 2018-05-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0008_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='reading_time',
            field=models.CharField(choices=[('anytime', 'Anytime'), ('morning', 'Morning'), ('midday', 'Midday'), ('evening', 'Evening')], default='anytime', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='template',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='type',
            field=models.CharField(blank=True, default='author', max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='images/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='settings',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='file',
            field=models.FileField(upload_to='issues/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='img',
            field=models.ImageField(upload_to='images/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
